# Generated by Django 5.1.2 on 2024-10-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=20)),
                ('Password', models.IntegerField(default='', max_length=10)),
            ],
        ),
    ]
